hmmclient passes valgrind

diff --git a/documentation/userguide/Makefile.in b/documentation/userguide/Makefile.in
--- a/documentation/userguide/Makefile.in
+++ b/documentation/userguide/Makefile.in
@@ -100,6 +100,7 @@ TEXFILES =\
 	macros.tex       \
 	main.tex         \
 	pipeline.tex     \
+	server.tex			\
 	tabular.tex      \
 	titlepage.tex    \
 	titlepage_daemon.tex \
@@ -107,7 +108,7 @@ TEXFILES =\
 
 .PHONY: pdf manpages clean distclean TAGS
 
-pdf:    Userguide.pdf Daemon_userguide.pdf
+pdf:    Userguide.pdf Daemon_userguide.pdf Server_userguide.pdf
 
 # We add ${srcdir} to TEXINPUTS, etc so we can build userguide in a build tree, with input files in source tree.
 Userguide.pdf: manpages ${TEXFILES}
@@ -131,6 +132,17 @@ Daemon_userguide.pdf: manpages ${TEXFILES}
 	@TEXINPUTS=${TEXINPUTS}:${srcdir} pdflatex daemon                                >> latex.log 2>&1 
 	@TEXINPUTS=${TEXINPUTS}:${srcdir} pdflatex daemon                                >> latex.log 2>&1 
 	@mv daemon.pdf Daemon_userguide.pdf
+
+Server_userguide.pdf: manpages ${TEXFILES}
+	@for prog in pdflatex bibtex; do \
+	  command -v $$prog >/dev/null 2>&1 || { echo >&2 "$$prog is required to build Userguide, but it's not installed. Aborting."; exit 1; } \
+	done
+	@echo "     LATEX Server_userguide.pdf  (see latex.log for output)"
+	@TEXINPUTS=${TEXINPUTS}:${srcdir} pdflatex server                               >  latex.log 2>&1 
+	@BIBINPUTS=${BIBINPUTS}:${srcdir} BSTINPUTS=${BSTINPUTS}:${srcdir} bibtex main >> latex.log 2>&1 
+	@TEXINPUTS=${TEXINPUTS}:${srcdir} pdflatex server                                >> latex.log 2>&1 
+	@TEXINPUTS=${TEXINPUTS}:${srcdir} pdflatex server                                >> latex.log 2>&1 
+	@mv server.pdf Server_userguide.pdf
 
 # manpages: convert man pages to LaTeX chapter in User Guide.
 #    uses PolyglotMan 3.2 "rman", and rmanprocess.py script in easel's devkit
@@ -167,7 +179,7 @@ distclean: clean
 	   done ;\
 	fi
 	-rm -f titlepage.tex copyright.tex manpages.tex easel_manpages.tex
-	-rm -f manpages_daemon.tex titlepage_daemon.tex
+	-rm -f manpages_daemon.tex titlepage_daemon.tex titlepage_server.tex
 	-rm -f Userguide.pdf
 	-rm -f Daemon_userguide.pdf
 	-rm -f Makefile
